name = "soda-recharge"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
DB_HOST = "141.140.14.61"
DB_PORT = "3306"
DB_NAME = "sqsd"
DB_USER = "sqsd"
DB_PASS = "sarFGSEKJdJrnaFc"
